# Workflow para desplegar contenido estático en GitHub Pages
name: Deploy ubicacion

on:
  push:
    branches: ["main"]  # Se ejecuta cuando haces push a la rama main
  workflow_dispatch:     # Permite ejecutarlo manualmente desde Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos de la carpeta ruleta
        uses: actions/upload-pages-artifact@v3
        with:
          path: ''  # ¡Aquí cambiamos de '.' a 'ruleta'!

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
